### ISSUE TITLE
Не работает git push через ssh на Linux Mint 18 (fork Ubuntu 16.04)

### ISSUE THREAD

**Issue by mubat** [zhovner/zaborona_help#68]

**Comment by zhovner** [comment]
Я не понимаю. Вы пытаетесь запушить прямо в этот репозиторий? 
Так нельзя, нужно сперва сделать форк и пушить в свой репозиторий, потом предложить изменения через pull request.

**Comment by Mubat** [comment]
@zhovner, нет. Я работают над своими проектами, использую git (репозиторий на bitbucket). И не могу пушить изменения. Работает только при отключенном VPN.

**Comment by zhovner** [comment]
Постарайтесь самостоятельно выяснить в чем проблема. Наш VPN не должен никак мешать битбакету. Возможно дело в DNS. Попробуйте выполнить ping до узла к которому вы подключаетесь.

**Comment by Mubat** [comment]
Что-то непонятное происходит. 
Так же не работает банальный `apt update`. Во время выполенения застревает на 
```0% [Connecting to archive.ubuntu.com (2001:67c:1560:8001::14)] [Connecting to security.ubuntu.com (2001:67c:1360:8001::17)]```

После посылания сигнала для остановки процесса выдается сообщение:

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 559, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1658, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.5/subprocess.py", line 1608, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/apt", line 149, in <module>
    return_code = subprocess.call(command)
  File "/usr/lib/python3.5/subprocess.py", line 561, in call
    p.kill()
  File "/usr/lib/python3.5/subprocess.py", line 1787, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.5/subprocess.py", line 1777, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process

```

**Comment by zhovner** [comment]
Скорее всего у вас неправильно устанавливаются маршруты для ipv6. Такая проблема уже поднималась здесь https://github.com/zhovner/zaborona_help/issues/50

**Comment by Mubat** [comment]
@zhovner указанное решение не подходит, потому как эта галочка уже стоит.
При включенном VPN выдаются маршруты:
```bash
oleg@colorsit-perpetuum:~$ ip -6 r
fe80::/64 dev enp3s5  proto kernel  metric 256  pref medium
default via fe80::485e:b71e:afd9:3119 dev enp3s5  proto static  metric 100  pref medium
```
При выключенном:
```shell
oleg@colorsit-perpetuum:~$ ip -6 r
2001:678:384::/48 via 2a00:1838:32:280::1 dev tun0  proto static  metric 50  pref medium
2620:10f:d000::/44 via 2a00:1838:32:280::1 dev tun0  proto static  metric 50  pref medium
2a00:1148::/32 via 2a00:1838:32:280::1 dev tun0  proto static  metric 50  pref medium
2a00:1838:32:280::1 dev tun0  proto kernel  metric 256  pref medium
2a00:1838:32:280::/112 dev tun0  proto kernel  metric 256  pref medium
2a00:1838:35:80::/64 via 2a00:1838:32:280::1 dev tun0  proto static  metric 50  pref medium
2a00:1838:37:6d::/64 via 2a00:1838:32:280::1 dev tun0  proto static  metric 50  pref medium
2a00:a300::/32 via 2a00:1838:32:280::1 dev tun0  proto static  metric 50  pref medium
2a00:b4c0::/32 via 2a00:1838:32:280::1 dev tun0  proto static  metric 50  pref medium
2a02:6b8::/32 via 2a00:1838:32:280::1 dev tun0  proto static  metric 50  pref medium
2a02:5180::/32 via 2a00:1838:32:280::1 dev tun0  proto static  metric 50  pref medium
2a03:2480::/33 via 2a00:1838:32:280::1 dev tun0  proto static  metric 50  pref medium
2a04:4b40::/29 via 2a00:1838:32:280::1 dev tun0  proto static  metric 50  pref medium
fe80::/64 dev enp3s5  proto kernel  metric 256  pref medium
fe80::/64 dev tun0  proto kernel  metric 256  pref medium
default via fe80::485e:b71e:afd9:3119 dev enp3s5  proto static  metric 100  pref medium
```

**Comment by zhovner** [comment]
Вместе с VPN у вас подключаются ipv6 dns. В обычное время ваш DNS сервер не отдает AAAA записей для доменов и все домены резолвятся на ipv4 адреса. При подключенном VPN вы начинаете получать ipv6 записи и система направляет запросы через этот маршрут: 

`default via fe80::485e:b71e:afd9:3119 dev enp3s5  proto static  metric 100  pref medium`

Вероятно, он выдается вашим роутером.
